// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<MyOpaqueType> createOpaque({required String message}) =>
    RustLib.instance.api.crateApiSimpleCreateOpaque(message: message);

Future<String> useOpaque({MyOpaqueType? object}) =>
    RustLib.instance.api.crateApiSimpleUseOpaque(object: object);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MyOpaqueType>>
abstract class MyOpaqueType implements RustOpaqueInterface {}
